### ISSUE TITLE
Desync with boost.context

### ISSUE THREAD

**Issue by Selmar** [septag/deboost.context#2]
Hi, 

I compared the assembly in the project (particularly `make_x86_64_ms_pe_masm.asm`), and it seems a out of date. From what I can tell, amongst the things that have been added is SEE register storage.

It could be useful to sync with boost.context, I think?

(I'm not very comfortable with assembly, or I would have sent a pull request.)

**Comment by septag** [comment]
oh! thanks for notifying me.
I will do it in the coming days.

**Comment by Selmar** [comment]
By the way, out of curiosity: I noticed you kept `BOOST_CONTEXT_EXPORT` around in the assembly, any particular reason for that?

**Comment by septag** [comment]
Not any specific reason except that I wanted to keep the original asm files intact for less maintenance, they are skipped by cmake anyway. 

btw, I updated to boost.context in 63476334fea6ccc4f2cc1de1d91257c3fe8b8fd3

**Comment by Selmar** [comment]
Ok. Awesome. 👍
